package:
  name: bam2fastq
  version: "1.1.0"

source:
  fn: bam2fastq-1.1.0.tgz
  url: http://gsl.hudsonalpha.org/static/software/bam2fastq-1.1.0.tgz

about:
  home: http://gsl.hudsonalpha.org/information/software/bam2fastq
  license: Apache License Version 2.0